[package]
name = "benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["env", "derive", "cargo"] }
color-eyre = "0.6.5"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tempfile = "3.20"
glob = "0.3"
toml = "0.8"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
uuid = { version = "1.16", features = ["v4"] }
serde_plain = "1.0.2"
bon = "3.8.1"
either = { version = "1.15.0", features = ["serde"] }
tap = "1.0.1"
color-print = "0.3.7"
tree-sitter = "0.25.10"
tree-sitter-rust = "0.24.0"
indoc = "2.0.7"
indent = "0.1.1"
partial_application = "0.2.1"
extfn = "0.1.3"
tree-sitter-traversal = "0.1.2"
rayon = "1.11.0"
itertools = "0.14.0"
glob-match = "0.2.1"
walkdir = "2.5.0"
derive_more = { version = "2.0.1", features = ["full"] }

[lints]
workspace = true
