[package]
name = "nudge"
version = "0.1.0"
edition = "2024"

[dependencies]
bon = "3.8.1"
clap = { version = "4.5.53", features = ["env", "derive", "cargo"] }
color-eyre = "0.6.5"
color-print = "0.3.7"
directories = "6.0.0"
glob = "0.3.3"
monostate = "1.0.2"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["preserve_order"] }
serde_yaml = "0.9.34"
shell-words = "1.1"
tap = "1.0.1"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
walkdir = "2.5.0"
annotate-snippets = "0.11"
tree-sitter = "0.25.10"
tree-sitter-rust = "0.24.0"
tree-sitter-typescript = "0.23.2"
derive_more = { version = "2.1.0", features = ["full"] }
itertools = "0.14.0"
indoc = "2.0.7"

[dev-dependencies]
pretty_assertions = "1.4.1"
simple_test_case = "1.3.0"
tempfile = "3.20"
xshell = "0.2.7"

[lints]
workspace = true
